source "https://rubygems.org"
gem "activesupport", ">=4.2.5"
gem "addressable", ">=2.5.1"
gem "nokogiri", ">=1.8.5"
gem "watir", ">=6.11.0"
gem "watir-scroll", ">=0.2.0"
gem "rspec", ">=3.7.0"
gem "coveralls", ">=0.8.21"
gem "pry", ">=0.11.3"
gem "rake", ">=12.3.1"
gem "simplecov", require: false # For Coveralls.
