WATIR_METHODS = [
  :a, :abbr, :abbrs, :address, :addresses, :animate, :animate_motion, :animate_motions,
  :animate_transform, :animate_transforms, :animates, :area, :areas, :article, :articles,
  :as, :aside, :asides, :audio, :audios, :b, :base, :bases, :bdi, :bdis, :bdo, :bdos,
  :blockquote, :blockquotes, :body, :bodys, :br, :brs, :bs, :button, :buttons, :canvas,
  :canvases, :caption, :captions, :checkbox, :checkboxes, :circle, :circles, :cite,
  :cites, :code, :codes, :col, :colgroup, :colgroups, :cols, :cursor, :cursors,
  :data, :datalist, :datalists, :datas, :dd, :dds, :defs, :defss, :del, :dels, :desc,
  :descs, :details, :detailses, :dfn, :dfns, :dialog, :dialogs, :discard, :discards,
  :div, :divs, :dl, :dls, :dt, :dts, :ellipse, :ellipses, :em, :element, :elements,
  :embed, :embeds, :ems, :field_set, :field_sets, :fieldset,
  :fieldsets, :figcaption, :figcaptions, :figure, :figures, :file_field, :file_fields,
  :font, :fonts, :footer, :footers, :foreign_object, :foreign_objects, :form, :forms,
  :frame, :frames, :frameset, :framesets, :g, :gs, :h1, :h1s, :h2, :h2s, :h3, :h3s,
  :h4, :h4s, :h5, :h5s, :h6, :h6s, :head, :header, :headers, :heads, :hgroup, :hgroups,
  :hidden, :hiddens, :hr, :hrs, :html, :htmls, :i, :iframe, :iframes, :image, :images,
  :img, :imgs, :input, :inputs, :ins, :inses, :is, :kbd, :kbds, :keygen, :keygens,
  :label, :labels, :legend, :legends, :li, :line, :linear_gradient, :linear_gradients,
  :lines, :link, :links, :lis, :main, :mains, :map, :maps, :mark, :marker, :markers,
  :marks, :menu, :menuitem, :menuitems, :menus, :mesh_gradient, :mesh_gradients,
  :mesh_patch, :mesh_patches, :mesh_row, :mesh_rows, :meta, :metadata, :metadatas,
  :metas, :meter, :meters, :mpath, :mpaths, :nav, :navs, :noscript, :noscripts,
  :object, :objects, :ol, :ols, :optgroup, :optgroups, :option, :options, :output,
  :outputs, :p, :param, :params, :path, :paths, :pattern, :patterns, :polygon,
  :polygons, :polyline, :polylines, :pre, :pres, :progress, :progresses, :ps, :q,
  :qs, :radial_gradient, :radial_gradients, :radio, :radios, :rect, :rects, :rp,
  :rps, :rt, :rts, :rubies, :ruby, :s, :samp, :samps, :script, :scripts, :section,
  :sections, :select, :select_list, :select_lists, :selects, :set, :sets, :small,
  :smalls, :source, :sources, :span, :spans, :ss, :stop, :stops, :strong, :strongs,
  :style, :styles, :sub, :subs, :summaries, :summary, :sup, :sups, :svg, :svgs,
  :switch, :switches, :symbol, :symbols, :table, :tables, :tbody, :tbodys, :td,
  :tds, :template, :templates, :text_field, :text_fields, :text_path, :text_paths,
  :textarea, :textareas, :tfoot, :tfoots, :th, :thead, :theads, :ths, :time, :times,
  :title, :titles, :tr, :track, :tracks, :trs, :tspan, :tspans, :u, :ul, :uls, :us,
  :use, :uses, :var, :vars, :video, :videos, :view, :views, :wbr, :wbrs
]
